spring.application.name=eureka-server
server.port=8761

# Eureka Server does not register itself or fetch the registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dashboard settings
eureka.server.enable-self-preservation=false
